config/routes.rb
Ocnews::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'app/users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  root 'app/posts#popular'

  namespace :app, path: '' do

    # /rss will always show recent posts (using /posts/newest?format=rss)
    get 'rss', to: 'posts#newest', defaults: { format: :rss }

    resources :posts, only: [:show, :new, :create, :destroy] do
      get 'newest', on: :collection, as: 'newest'
      get 'popular', on: :collection, as: 'popular'
      post 'like', on: :member, as: 'like'
    end

    resources :users, only: [:show, :index]
    resources :comments, only: [:show, :create] do
      post 'like', on: :member, as: 'like'
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PopularSorting

  # Accessors
  attr_accessor :future_child_of

  # Use Parole
  acts_as_commentable
  acts_as_comment

  # Use Awesome Nested Set
  acts_as_nested_set

  # Use Emotions
  acts_as_emotive

  # Validations
  validates :comment, presence: true
  validates :commenter, presence: true
  validates :commentable, presence: true

  # Callbacks
  after_create :move_self_as_a_child, if: -> { future_child_of.present? }
  before_create :set_root_id
  after_create :denormalize_comments_count
  after_create :denormalize_root_comments_count

private

  def set_root_id
    if future_child_of.is_a?(Comment)
      self.root_id = self.future_child_of.root_id
      self.root_type = self.future_child_of.root_type
    else
      self.root_id = self.commentable.id
      self.root_type = self.commentable.class.to_s
    end
  end

  def move_self_as_a_child
    self.move_to_child_of(self.future_child_of) if future_child_of.is_a?(Comment)
  end

  def denormalize_comments_count
    return if self.parent.nil?

    Comment.where(id: self.ancestors.pluck(:id))
           .where('id != ?', self.parent.id)
           .update_all('comments_count = comments_count + 1')
  end

  def denormalize_root_comments_count
    comments_count = Comment.where(root_id: self.root_id).count
    root_type.constantize.find(self.root_id).update_column(:comments_count, comments_count)
  end
end

app/controllers/app/comments_controller.rb
class App::CommentsController < App::ApplicationController
  before_action :ensure_current_user, only: [:create, :like]
  before_action :fetch_comment, only: [:show, :like]

  # POST /comments/new
  def create
    @comment = current_user.comments.build
    @comment.assign_attributes(comment_params)
    @comment.future_child_of = @comment.commentable

    if @comment.save
      url = :back
      url = app_post_path(@comment.commentable) if @comment.commentable.is_a?(Post)

      current_user.like_comment!(@comment)

      if @comment.commentable_type == "Comment"
        original_commentable = fetch_original_commentable
        original_commentable.class.name.constantize.increment_counter(:comments_count, original_commentable.id)
      end

      redirect_to url, notice: t('.notice')
    else
      render :new
    end
  end

  # GET /comments/:id
  def show
    @comments = @comment.comments
  end

  # POST /comments/:id/like
  def like
    current_user.like_comment!(@comment)
    redirect_to :back
  end

private

  def fetch_original_commentable
    current_commentable = Comment.find(@comment.commentable_id)

    until current_commentable.commentable_type != "Comment" do
      current_commentable = Comment.find(current_commentable.commentable_id)
    end

    current_commentable.commentable_type.constantize.find(current_commentable.commentable_id)
  end

  def fetch_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    permitted_parameters = [:comment, :commentable_id, :commentable_type]
    params.require(:comment).permit(*permitted_parameters)
  end
end

app/views/app/comments/_form.html.erb
<% if user_signed_in? %>
  <div role="form" class="comment-form" <%= ' hidden' if comment.commentable_type == 'Comment' %>>
    <%= form_for comment, url: app_comments_path do |f| %>
      <%= render_error_messages(f.object) %>
      <%= f.hidden_field :commentable_id %>
      <%= f.hidden_field :commentable_type %>
      <div class="form-group">
        <%= f.label :comment, :class => "control-label" %>
        <%= f.text_area :comment, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= submit_tag nil, :class => "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/app/comments/_list.html.erb
<ol class="comments-list">
  <% comments.each do |comment| %>
    <%= render partial: 'app/comments/mini', locals: { threaded: true, comment: comment } %>
  <% end %>
</ol>

app/views/app/comments/_mini.html.erb
<% threaded ||= false %>

<li class="comment">
  <% present comment do |comment| %>
    <div class="meta">
      <%= comment.upvote_link(current_user) %>
      <%= comment.author_link %>
      , il y a
      <%= link_to time_ago_in_words(comment.created_at), app_comment_path(comment) %>
      - <%= comment.points_count %>
      <a href="javascript://" class="reply">reply</a>
    </div>
    <div class="body">
      <%= comment.formatted_comment(:markdown) %>
    </div>

    <div class="comment-box">
      <%= render partial: 'app/comments/form', locals: { comment: comment.comments.build } %>
    <div>

    <% threaded && comment.with_comments do %>
      <ul>
        <%= render partial: 'app/comments/list', locals: { comments: comment.comments.popular } %>
      </ul>
    <% end %>
  <% end %>
</li>

app/views/app/comments/new.html.erb
<% if @comment.commentable.is_a?(Post) %>
  <%= render partial: 'app/posts/mini', locals: { post: @comment.commentable } %>
<% end %>
<%= render partial: 'app/comments/form', locals: { commentable: @comment } %>

app/views/app/comments/show.html.erb
<% content_for :current_section, :comment %>

<ol class="comments-list">
  <%= render partial: 'mini', locals: { comment: @comment } %>
</ul>

<%= render partial: 'app/comments/form', locals: { comment: @comment.commentable.comments.build } %>
<%= render partial: 'app/comments/list', locals: { comments: @comments.popular } %>