config/routes.rb
Ocnews::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'app/users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  root 'app/posts#popular'

  namespace :app, path: '' do

    # /rss will always show recent posts (using /posts/newest?format=rss)
    get 'rss', to: 'posts#newest', defaults: { format: :rss }

    resources :posts, only: [:show, :new, :create, :destroy] do
      get 'newest', on: :collection, as: 'newest'
      get 'popular', on: :collection, as: 'popular'
      post 'like', on: :member, as: 'like'
    end

    resources :users, only: [:show, :index]
    resources :comments, only: [:show, :create] do
      post 'like', on: :member, as: 'like'
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ExternalMetadata
  include PopularSorting

  # Use Parole
  acts_as_commentable

  # Use Emotions
  acts_as_emotive

  # Use FriendlyId
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Associations
  belongs_to :user

  # Validations
  validates :url, http: true
  validates :url, fresh_url: true, on: :create
  validates :title, presence: true
  validates_with PostValidator

  # Scopes
  scope :newest, lambda { order('created_at DESC') }

  def virgin?
    (like_emotions_count - 1) + comments.count <= 0
  end
end

app/controllers/app/posts_controller.rb
class App::PostsController < App::ApplicationController
  before_action :ensure_current_user, only: [:create, :like, :new]
  before_action :fetch_post, only: [:show, :like, :destroy]

  # GET /
  # GET /posts
  def popular
    @posts = Post.popular.page(params[:page]).includes(:user)

    respond_to do |format|
      format.html

      # /posts/popular.rss
      format.rss{ render layout: false }
    end
  end

  # GET /posts/newest
  def newest
    @posts = Post.newest.page(params[:page]).includes(:user)

    respond_to do |format|
      format.html

      # /posts/newest.rss
      format.rss{ render layout: false }
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # POST /posts/new
  def create
    @post = current_user.posts.build
    @post.assign_attributes(post_params)

    if @post.save
      current_user.like_post!(@post)
      redirect_to newest_app_posts_path, notice: t('.notice')
    else
      render :new
    end
  end

  # GET /posts/:id
  def show
    @comments = @post.comments.popular
    @comment = @post.comments.build(commenter: current_user)
  end

  # DELETE /posts/:id
  def destroy
    action = PostDeleter.new(current_user, @post).run!

    if action
      redirect_to :back
    else
      redirect_to :back, notice: t('.unauthorized')
    end
  end

  # POST /posts/:id/like
  def like
    current_user.like_post!(@post)
    redirect_to :back
  end

private

  def fetch_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    permitted_parameters = [:title, :url, :description]
    params.require(:post).permit(*permitted_parameters)
  end
end

app/views/app/posts/_list.html.erb
<ol start="<%= @posts.offset_value + 1 %>" class="posts-list">
  <% @posts.each do |post| %>
    <%= render partial: 'app/posts/mini', locals: { post: post } %>
  <% end %>
</ol>

<% unless @posts.last_page? %>
  <%= link_to_next_page(@posts, 'Plus de ragout', class: 'next-page') %>
<% end %>

app/views/app/posts/_mini.html.erb
<li class="post">
  <% present post do |post| %>
    <div class="link">
      <%= post.upvote_link(current_user) %>
      <% if post.url.blank? %>
        <%= link_to post.title, app_post_path(post) %>
      <% else %>
        <%= link_to post.title, post.url %>
      <% end %>
      <%= post.destroy_link(current_user) %>

      <% post.with_url do %>
        <span class="domain"><%= post.domain %></span>
      <% end %>
    </div>

    <div class="meta">
      <span class="points-count"><%= post.points_count %></span>
      <span class="comments-count"><%= post.comments_count %></span>
      <span class="author-link"><%= post.author_link %></span>
      <span class="timestamp" title="<%= post.created_at %>">
        <%= time_ago_in_words(post.created_at) %>
      </span>
    </div>
  <% end %>
</li>

app/views/app/posts/index.haml
= render partial: 'list', locals: { posts: @posts }

app/views/app/posts/new.html.erb
<% content_for :current_section, :submit %>
<% content_for :page_title, t('.page_title') %>

<%= form_for @post, url: app_posts_path do |f| %>
  <%= render_error_messages(f.object) %>

<form role="form">

  <div>
    <div class="half">
      <%= f.label :title, :class => "control-label" %>
      <%= f.text_field :title, :class => "form-control" %>
    </div>

    <div class="half">
      <%= f.label :url, :class => "control-label" %>
      <%= f.url_field :url, :class => "form-control" %>
    </div>
  </div>

  <div>
    <%= f.label :description, :class => "control-label" %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

  <div>
    <%= submit_tag nil, :class => "btn btn-primary"%>
  </div>
  </ul>
<% end %>

app/views/app/posts/newest.html.erb
<% content_for :current_section, :newest %>
<% content_for :page_title, t('.page_title') %>

<%= render partial: 'list', locals: { posts: @posts } %>

app/views/app/posts/popular.html.erb
<% content_for :current_section, :popular %>
<% content_for :page_title, t('.page_title') %>

<%= render partial: 'list', locals: { posts: @posts } %>

app/views/app/posts/show.html.erb
<% content_for :current_section, :post %>

<% present @post do |post| %>
  <ul class="posts-list">
    <%= render partial: 'mini', locals: { post: @post } %>
    <% post.with_description do %>
      <p><%= post.formatted_description(:markdown) %></p>
    <% end %>
  </ul>

  <hr>

  <%= render partial: 'app/comments/form', locals: { comment: @comment } %>

  <%= render partial: 'app/comments/list', locals: { comments: @comments.popular } %>
<% end %>