config/routes.rb
Ocnews::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'app/users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  root 'app/posts#popular'

  namespace :app, path: '' do

    # /rss will always show recent posts (using /posts/newest?format=rss)
    get 'rss', to: 'posts#newest', defaults: { format: :rss }

    resources :posts, only: [:show, :new, :create, :destroy] do
      get 'newest', on: :collection, as: 'newest'
      get 'popular', on: :collection, as: 'popular'
      post 'like', on: :member, as: 'like'
    end

    resources :users, only: [:show, :index]
    resources :comments, only: [:show, :create] do
      post 'like', on: :member, as: 'like'
    end
  end
end

app/views/shared/_error_messages.html.erb
<div class="alert alert-danger">
  <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<footer>
  <hr />
  <p>
    <a href="/">OpenCode News</a> est une initiative de la communauté de
    développeurs de l'<a href="http://opencode.ca">OpenCode</a>, dans le but
    d'échanger entre <i>trippeux</i> de code.
  </p>
  <p>We <a href="https://github.com/opencodeqc/ocn">♥</a> code.</p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navigation" role="navigation">
  <div>
    <%= link_to t('.title'), root_path, class: 'ocn-brand' %>

    <ul class="site-nav" id="main-nav">
      <li class="<%= navigation_class(:popular) %>">
        <%= link_to t('.popular'), root_path %>
      </li>

      <li class="<%= navigation_class(:newest) %>">
        <%= link_to t('.newest'), newest_app_posts_path %>
      </li>

      <% if user_signed_in? %>
        <li class="<%= navigation_class(:submit) %>">
          <%= link_to t('.submit'), new_app_post_path %>
        </li>
      <% end %>

      <li class="<%= navigation_class(:users) %>">
        <%= link_to t('.users'), app_users_path %>
      </li>

      <li>
        <% if user_signed_in? %>
          <li><%= link_to t('.logout'), logout_path %> </li>
        <% else %>
          <li><%= link_to t('.login'), user_omniauth_authorize_path(:github) %></li>
        <% end %>
      </li>
    </ul>

    <button id="btn-toggle-nav"></button>

    <%= render partial: 'app/users/nav_profile' %>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-error">
    <%= alert %>
  </p>
<% end %>