config/routes.rb
Ocnews::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'app/users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  root 'app/posts#popular'

  namespace :app, path: '' do

    # /rss will always show recent posts (using /posts/newest?format=rss)
    get 'rss', to: 'posts#newest', defaults: { format: :rss }

    resources :posts, only: [:show, :new, :create, :destroy] do
      get 'newest', on: :collection, as: 'newest'
      get 'popular', on: :collection, as: 'popular'
      post 'like', on: :member, as: 'like'
    end

    resources :users, only: [:show, :index]
    resources :comments, only: [:show, :create] do
      post 'like', on: :member, as: 'like'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title><%= page_title(base: t('.base_title')) %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= auto_discovery_link_tag(:rss, app_rss_url) %>
    <%= auto_discovery_link_tag(:rss, newest_app_posts_url(format: :rss)) %>
    <%= auto_discovery_link_tag(:rss, popular_app_posts_url(format: :rss)) %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
  </head>
  <body class="nav-close">
    <%= render partial: 'shared/nav' %>
    <div class="progress_bar"></div>

    <div class="container">
      <%= render partial: 'shared/notices' %>
      <%= yield %>
      <%= render partial: 'shared/footer' %>
    </div>
  </body>
</html>